"""Stable machine-readable codes at the shared authority boundary."""

from enum import Enum


class RefusalCode(str, Enum):
    REQUEST_INVALID = "REQUEST_INVALID"
    UNKNOWN_AUTHORITY_FIELD = "UNKNOWN_AUTHORITY_FIELD"
    ARBITRARY_CALL_REFUSED = "ARBITRARY_CALL_REFUSED"
    ACTION_NOT_ALLOWED = "ACTION_NOT_ALLOWED"
    NETWORK_NOT_ALLOWED = "NETWORK_NOT_ALLOWED"
    ASSET_NOT_ALLOWED = "ASSET_NOT_ALLOWED"
    CONTRACT_NOT_ALLOWED = "CONTRACT_NOT_ALLOWED"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    MODULE_NOT_ALLOWED = "MODULE_NOT_ALLOWED"
    AMOUNT_INVALID = "AMOUNT_INVALID"
    AMOUNT_LIMIT_EXCEEDED = "AMOUNT_LIMIT_EXCEEDED"
    MAX_FEE_REQUIRED = "MAX_FEE_REQUIRED"
    MAX_FEE_EXCEEDED = "MAX_FEE_EXCEEDED"
    POLICY_VERSION_MISMATCH = "POLICY_VERSION_MISMATCH"
    POLICY_AUTHORITY_DISABLED = "POLICY_AUTHORITY_DISABLED"
    ACTION_ID_INVALID = "ACTION_ID_INVALID"
    ACTION_ALREADY_ACTIVE = "ACTION_ALREADY_ACTIVE"
    ACTION_MUTATED = "ACTION_MUTATED"
    ACTION_REPLAYED = "ACTION_REPLAYED"
    REQUEST_TEMPORARILY_BLOCKED = "REQUEST_TEMPORARILY_BLOCKED"


class SecurityCode(str, Enum):
    IPC_INVALID_REQUEST = "IPC_INVALID_REQUEST"
    SCHEMA_VERSION_UNSUPPORTED = "SCHEMA_VERSION_UNSUPPORTED"
    POLICY_INTEGRITY_FAILED = "POLICY_INTEGRITY_FAILED"
    POLICY_STATE_INVALID = "POLICY_STATE_INVALID"
    ACTION_STATE_INVALID = "ACTION_STATE_INVALID"
    SIGNING_DISABLED = "SIGNING_DISABLED"
    REQUEST_CONTROL_STATE_INVALID = "REQUEST_CONTROL_STATE_INVALID"
    JOURNAL_STATE_INVALID = "JOURNAL_STATE_INVALID"
    JOURNAL_WRITE_FAILED = "JOURNAL_WRITE_FAILED"
